import accessoriesqualities from "./data/accessoriesqualities.json";
import armorqualities from "./data/armorqualities.json";
import weaponqualities from "./data/weaponqualities.json";
import heroicskills from "./data/heroicskills.json";
import heroicskillshighfantasy from "./data/heroicskillshighfantasy.json";
import heroicskillstechnofantasy from "./data/heroicskillstechnofantasy.json";
import heroicskillsnaturalfantasy from "./data/heroicskillsnaturalfantasy.json";
import qualitiesset1 from "./data/qualitiesset1.json";
import heroicstyles from "./data/heroicstyles.json";
import npcspells from "./data/npcspells.json";
import quirksbonus from "./data/quirksbonus.json";
import quirkshighfantasy from "./data/quirkshighfantasy.json";
import quirksnaturalfantasy from "./data/quirksnaturalfantasy.json";
import quirkstechnofantasy from "./data/quirkstechnofantasy.json";

export default {
  sample: [
    "When the attack roll's INS die rolls 10+, regain 3 MP.",
    "After regaining HP from a potion, this weapon gains +1 accuracy until the end of your next turn.",
    "When you regain an amount of HP exceeding your missing HP by 20 or more, regain 5 MP.",
    "When attacking with this weapon, if your target hasn't yet taken an action this round, deal +4 damage.",
    "When your attack with this weapon causes a creature to enter Crisis, the ally with the least MP regains 5 MP.",
    "When an ally reduces a creature to 0 HP, your next attack with this weapon has +1 accuracy and +2 damage.",
    "When you reduce a creature to 0 HP with this weapon, the ally with the lowest MP regains 5 MP.",
    "When an ally surrenders, regain 10 HP.",
    "When you reduce a creature to 0 HP with this weapon, your next attack with this weapon deals +5 damage.",
    "Targets Magic Defense instead of Defense.",
    "+2 Defense, counts as shield. When the Accuracy Check is even, +2 to the total. When the Accuracy Check is odd, -2 to the total.",
    "When you hit a single creature with this weapon, both of you suffer weak until one of you recovers from the status.",
    "If you have a shield equipped, this weapon deals +2 damage.",
    "When you make an attack with this weapon and hit, get +1 to your next Accuracy Check. When you miss, get +1 to your next Magic Check.",
    "When you enter Crisis, this weapon's damage type changes randomly for this Scene. Roll 1d6: 1, fire, 2, earth, 3, bolt, 4, ice, 5, poison, 6, physical.",
    "When you transform your weapon immediately after an attack on the same turn, deal an extra 5 damage to the target(s) of the attack.",
    "When you hit a creature who has not yet taken their turn this round with this weapon, they become slow until the end of the round.",
    "When you invoke a Bond of affection to alter this weapon's Accuracy Check, the attack inflicts dazed.",
    "Deals 5 extra damage to Humanoids.",
    "While suffering from a status effect other than shaken, you're immune to shaken.",
    "You have resistance to physical damage during the first round of combat.",
    "At the start of each of your turns, you must choose an ally; they lose 5 MP, and you gain 5 MP.",
    "When a creature suffering from weak is hit by this weapon and hasn't taken a turn yet this round, they also suffer slow.",
    "While you are poisoned, your Might die size does not decrease, and your Accuracy checks with this weapon have a +2 bonus.",
    "At the start of the fourth conflict round, this weapon deals +5 damage for the rest of the Scene.",
    "When you hit one or more slow targets with this weapon, you regain 5 HP.",
    "When in Crisis, successful attacks against targets also in Crisis inflict weak.",
    "While you aren't dazed, attacks with this weapon have multi (2) and you suffer dazed if you hit.",
    "Attacking a shaken ally with this weapon removes that status effect from them.",
    "If you are proficient with martial melee weapons, you may wield this weapon in two hands. While you do so, it deals +6 damage.",
    "While in Crisis, this weapon has +1 accuracy per status effect you're suffering from.",
    "After attacking with this weapon, your Might die size increases by one and your Dexterity die size decreases by one until the end of your next turn.",
    "When a creature on the scene falls to 0 HP, the ally with the least MP regains 5 MP.",
    "When you reduce a creature to 0 HP with this weapon, you and all allies regain 5 HP.",
    "You may choose to target randomly (enemies and allies included). If you hit an ally, restore [ HR + 12 ] HP instead of dealing damage. If you hit an enemy, deal +2 damage.",
    "+2 Magic Defense. The first time your MP hits 0 during a conflict scene, you instantly regain 10 MP.",
    "When you roll a critical success on this weapon's Accuracy Check, you may spend the opportunity to cause each of the attack's target(s) to lose 30 MP.",
    "On hit, inflict 1 Talisman for the Scene (max 2). A creature with 1 Talisman deals +2 damage, a creature with 2 suffers weak and cannot lose that status.",
    "When in Crisis, successful attacks against targets also in Crisis inflict shaken.",
    "Damage dealt by this weapon ignores Resistances. If it strikes an Immunity, you take 10 damage.",
    "When an ally takes damage, gain 1 Punishing (max 5). When making an Accuracy Check with this weapon, spend 5 Punishing to set one die to 10, even if impossible (such as a 10 on a d8).",
    "The first time you target an creature in a conflict Scene, you gain a +2 bonus to your Accuracy Check against them.",
    "When this weapon's Accuracy Check has an odd total, you lose 10 MP. When it has an even total, you gain 10 MP.",
    "During the third conflict round; this weapon inflicts dazed, and if you end your turn without using it to attack, you lose 10 HP.",
    "When you hit one or more target(s) with this weapon, you may forgo dealing damage. If you do, all earth damage they take is increased by 5 until the start of your next turn.",
    "When you hit a guarding creature with this weapon, they suffer slow.",
    "While in Crisis, attacking with this weapon grants 1 Charge for the Scene. When you Guard, you may recover Charge * 5 HP, then spend all Charge.",
    "When you hit a creature in cover with this weapon, they suffer dazed.",
    "When you hit one or more target(s) with this weapon, you may deal -8 damage. If you do, all fire damage they take is increased by 5 until the start of your next turn.",
    "When you hit one or more creatures with this weapon, each of them loses 5 MP.",
    "When you miss with this weapon, the next attack you make with it in the same Scene has multi (2).",
    "When you hit a creature at full HP with this weapon, you recover 5 HP.",
    "The first time you enter Crisis during a conflict scene, you instantly regain 10 HP.",
    "Attacks with this weapon have multi (3), targeting yourself and two others of your choice.",
    "When you use the Heal spell on targets other than yourself, you can reduce the HP recovery by 10 to restore 10 MP to all targets.",
    "Deals 5 extra damage while you have 0 MP.",
    "Deals 5 extra damage and inflicts weak to enemies of the Plant species.",
    "While you're in Crisis, this weapon has multi (2).",
    "When attacking with this weapon, the HR doesn't increase damage; instead, regain HP equal to the HR when you hit one or more targets.",
    "When you reduce an enemy to 0 HP with this weapon, recover 2 HP per status effect they were suffering from.",
    "When you hit a creature at full HP with this weapon, you deal +5 damage.",
    "When an creature hits you with a melee attack, they lose 5 Mind Points.",
    "Strikes twice as per two-weapon fighting rules, grants +2 Magic Defense. The last target hit by this weapon deals -5 damage to you until the end of their next turn.",
    "When you deal 25+ damage to a target with a spell, regain 5 MP.",
    "When you hit one or more targets suffering from one or more status effects with this weapon, you regain 5 MP.",
    "Before attacking with this weapon, the user becomes slow. When the DEX dice in the accuracy check rolls between 1 and 3, the target becomes slow.",
    "When you reduce a creature to 0 HP with this weapon, any number of creatures of your choice lose 15 MP.",
    "Attacks with this weapon treat the target's Defense as being equal to their current Willpower die size.",
    "Grants +2 Magic Defense. The MP cost of medium and high frequency Magichants is reduced by 5 MP.",
    "+2 MDef in Arcane form. When you end your turn with this weapon in Arcane form, inflict Roots on one enemy. If you hit a creature with Roots with the Heavy form, remove Roots and inflict slow.",
    "When using an elemental shard, you can make a free attack with this weapon.",
    "After being hit by an creature's attack, gain 1 Gazing (max 4). At the start of your turn, you may spend 4 Gazing to make a free attack with this weapon.",
    "Attacking with this weapon inflicts dazed if the target has an Insight of d10 or higher.",
    "Attacks twice as per two-weapon fighting rules. When you hit one or more creatures in Crisis with this weapon, you regain 5 HP.",
    "When one of your attributes is raised by a die size, choose a creature; they take 10 damage and receive the same attribute die size increase for the same duration.",
    "You may use your action to ready a pounce. If you do, you must use your next action to attack with this weapon. If that attack hits, inflict slow and weak.",
    "When the target is suffering from shaken or weak, this weapon gains +3 accuracy.",
    "When you miss an attack with this weapon, you lose 10 MP, and all allies regain 5 MP.",
    "When you hit a creature who has not yet taken their turn this round with this weapon, and they are in Crisis or at 0 HP after the attack, you regain 5 HP.",
    "When you attack with two-weapon fighting and miss with your first attack, this weapon inflicts weak and deals +5 damage during the same turn.",
    "Strikes twice as per two-weapon fighting rules in alt form. When you use the Bone Crusher skill with an attack from this weapon while suffering from any status effects, your target loses 10 MP.",
    "Deals +5 damage while a single ally (but not two or more) is in Crisis.",
    "Each taget hit by this weapon has a -2 penalty to their next Accuracy Check.",
    "When you recover 10+ MP, recover 10 fewer MP, and your next attack with this weapon before the end of your next turn deals +10 damage.",
    "Grants +2 Defense, counts as shield. When you hit one or more targets with this weapon, a random ally regains 5 HP.",
    "When you spend 20 or more MP on a single effect in conflict, your next attack with this weapon before the end of your next turn deals +5 damage.",
    "If you have more MP than the target, this weapon deals +5 damage.",
    "Inflicts 10 Sparks on each creature hit. Creatures with Sparks cannot suffer dazed or slow, but anyone who hits them with a weapon attack may reduce the Sparks by 5 and regain that much MP.",
    "The target of this attack suffers slow. This weapon's attacks can't gain multi.",
    "When a target with physical Resistance is hit by this weapon, they lose that Resistance.",
    "As long as you have three or more bonds of affection or mistrust, you regain 5 Hit Points and Mind Points when you hit one or more creatures with this weapon.",
    "Strikes twice as per two-weapon fighting rules, grants +2 Def, counts as shield. If you hit two creatures at once with this weapon, you gain immunity to bolt damage until the start of your next turn.",
    "Each target hit by this weapon suffers poisoned if you have a Bond with them.",
    "When your attack with this weapon triggers the Personal Touch skill, each target who suffers the extra damage also becomes dazed.",
    "This weapon's attacks have multi (2), deal 5 fewer damage to plants, and 5 extra damage to beasts.",
    "When you enter Crisis for the first time in conflict, you may make a free attack against the creature who put you into Crisis. On a hit, they perform one fewer action (minimum 0) on their next turn.",
    "When using the Guard action in conflict to cover an ally in Crisis, they regain 5 HP and MP.",
    "Once per turn on your turn, you can spend 5 MP to bloom one of this weapon's buds. When the fourth bud blooms, you regain 30 HP and MP.",
    "Each target struck by this weapon suffers slow if they were already suffering from any status effect.",
    "When an ally enters Crisis for the first time in a Scene, deal 5 poison damage to any number of creatures you choose.",
    "When you hit a flying target with this weapon, you may force that target to land immediately.",
    "Deals 5 extra damage and inflicts enraged to Beasts.",
    "Grants +2 Magic Defense. For every creature on the scene who is at full HP, deal +2 damage (max +10).",
    "You have resistance to earth and air damage.",
    "When you hit one or more creatures with this weapon, the next spell they cast during this Scene costs an additional 15 MP.",
    "If either accuracy dice plus the accuracy bonus would exceed the target's Defense without the addition of the other, the attack deals +5 damage.",
    "Each time you make an attack with this weapon, gain 1 Logging. On the fourth round, your first attack with this weapon gets +1 accuracy and +4 damage per Logging.",
    "+2 Magic Defense. When dealing damage with this weapon during conflict, you can instead heal the target HP or MP equal to 5 + the damage you would've dealt.",
    "+2 Defense and counts as shield in alternate form. When entering Crisis for the first time in a Scene, deal 10 physical damage to any number of creatures you choose.",
    "Attacks made by this weapon have multi (2).",
    "After regaining HP or MP from a potion, your next attack with this weapon in the same Scene inflicts poisoned.",
    "This weapon deals +5 damage to enemies who haven't damaged its user in this Scene, and can target them even if they're benefitting from flight or cover.",
    "While you aren't in Crisis, attacks made by this weapon have multi (2) and ignore Resistances.",
    "Your weapon attacks ignore Immunities and Resistances.",
    "Strikes twice as per two-weapon fighting rules. Each creature in Crisis suffers dazed when hit by this weapon.",
    "Strikes twice as per two-weapon fighting rules. +2 Magic Defense. If you have three or more bonds of loyalty or inferiority, each target hit by this weapon suffers enraged.",
    "When attacking, you can grant this weapon multi (3). If you do, each creature hit by this weapon has their attributes increase by one die size until the end of your next turn.",
    "Deals +5 damage to creatures who are flying or in cover, can target them, and immediately ends both effects on a hit.",
    "After a creature hits you with a ranged attack, you deal 5 air damage to that creature (after the attack is resolved).",
    "Hitting an creature with this weapon reduces their affinity to dark for the Scene (from Absorption to Immunity, Immunity to Resistance, Resistance to none).",
    "Damage dealt by this weapon changes to whichever type is most effective between light or dark.",
    "When you end your turn without using this weapon, it deals +5 damage on your next turn.",
    "After an attack with this weapon is resolved, you and any creatures of your choice gain resistance to air damage until the end of your next turn.",
    "+2 Def, counts as shield. After you reduce a creature to 0 HP with this weapon, your next attack with this weapon during the same Scene gains multi (2) and inflicts slow.",
    "After hitting at least one creature with this weapon, both you and each target hit take 5 extra damage the next time damage is taken.",
    "When you hit one or more creatures with this weapon, choose an ally and raise their Willpower by one die size until the start of your next turn.",
    "When you hit one or more creatures with this weapon, regain 10 MP.",
    "After you reduce a creature to 0 HP with this weapon, your next attack with this weapon during the same Scene inflicts enraged.",
    "When using the Guard action in conflict to cover an ally, you and they both regain 5 MP.",
    "Each target hit by this weapon, if their Insight die size is lower than yours, suffers dazed and takes 5 extra damage.",
    "At the start of your turn, if you're suffering from three or more status effects, you become immune to all status effects until the start of your next turn.",
    "+2 Defense/Magic Defense, counts as shield. When an creature deals damage to you, Laetitia's damage type changes to the same type you just took.",
    "When you hit one or more creatures with this weapon, mark one as the Villain until the end of their next turn. When the Villain damages you, your next attack with this weapon gains multi (3).",
    "After you enter Crisis for the first time in a conflict scene, take an additional action on your next turn (max 2).",
    "After you reduce a creature to 0 HP with this weapon, your next attack with this weapon during the same Scene inflicts poisoned.",
    "Once per Scene when you make an attack with this weapon, your next attack with this weapon in that Scene has multi (4). After that, all your non-free attacks target a random ally for this Scene.",
    "Inflicits poisoned to each creature hit. At the start of the third round, you become poisoned and cannot lose the status effect until the end of the Scene.",
    "When you hit one or more creatures with this weapon, you can end all spells affecting them with a duration of Scene.",
    "Each target hit by this weapon suffers dazed.",
    "When you hit one or more creatures with this weapon, they suffer weak and your Might die size increases by one until the end of your next turn.",
    "This weapon deals +5 damage if you are in Crisis, and a futher +5 damage if your target is in Crisis.",
    "When an creature with 10 (+5 per status they're suffering from) or less HP is targeted by this weapon, they lose all HP.",
    "While you're in Crisis, you and all allies deal +2 damage.",
    "When targeting one or more creatures with this weapon, choose one of their basic attacks; this attack copies its special effect(s).",
    "When casting spells on two targets, the weakest of the targets' affinities applies to both (so if one creature is VU fire and one is IM fire, they're both treated as VU fire).",
    "When you hit one or more creatures with this weapon, you regain 10 HP.",
    "Strikes twice as per two-weapon fighting rules. When you deal damage to someone suffering from the shaken status effect, you deal +5 damage.",
    "Always targets every creature on the Scene suffering from a status effect.",
    "+2 Def, counts as shield. Strikes twice as per two-weapon fighting rules. While this weapon is equipped, your Might increases by one die size (max d12).",
    "When you take the attack action, you can also have one ally make a free attack with +1 accuracy and +4 damage.",
    "Typless damage. When you hit a creature with this weapon and they enter Crisis, you may transform your weapon and perform a free attack against them, in any order.",
    "Attacks with this weapon have multi (3).",
    "Each target hit by this weapon becomes poisoned.",
    "For every creature on the scene who is in Crisis, deal +2 damage. May target flying creatures.",
    "Once per conflict, you can grant a surrendered ally a single turn immediately after your own.",
    "Each target hit by this weapon becomes enraged.",
    "You gain a +1 bonus to your Defense and Magic Defense.",
    "Each target hit suffers slow (round 1), weak (round 2), shaken (round 3) or dazed (round 4) depending on the current round. Inflicts no status at round 5+.",
    "+2 Def/Mdef, counts as shield. When you make an attack with this weapon while at 0 MP, each target hit suffers dazed, shaken and weak.",
    "You absorb dark damage.",
    "When you deal damage with this weapon, you can halve the damage, deal that amount of damage to the target and two more, and recover 5 HP.",
    "When a major or supreme Villain is struck by this weapon, deal +5 damage and restore 5 HP and MP to all allies.",
    "Strikes twice as per two-weapon fighting rules. Deals +5 damage to targets of Level 30 or higher.",
    "+2 Def/Mdef, counts as shield. Allies may replace one or both of their attribute dice with yours when making Accuracy Checks. This weapon doesn't make Accuracy Checks.",
    "Each target hit by this weapon suffers shaken, and at the start of each of your turns you may cause each shaken creature on the Scene to lose 5 HP.",
    "You are immune to light damage, and this weapon deals +10 damage to enemies with full HP.",
    "Attacks twice as per two-weapon fighting rules. When a creature with one or more Vulnerabilities enters Crisis, this weapon's damage type changes to match one of their Vulnerabilities.",
    ...accessoriesqualities.data.map((item) => item.description),
    ...armorqualities.data.map((item) => item.description),
    ...weaponqualities.data.map((item) => item.description),
    ...heroicskills.data.map((item) => item.description),
    ...heroicskillshighfantasy.data.map((item) => item.description),
    ...heroicskillstechnofantasy.data.map((item) => item.description),
    ...heroicskillsnaturalfantasy.data.map((item) => item.description),
    ...qualitiesset1.data.map((item) => item.description),
    ...heroicstyles.data.map((item) => item.description),
    ...npcspells.data.map((item) => item.description),
    ...quirksbonus.data.map((item) => item.description),
    ...quirkshighfantasy.data.map((item) => item.description),
    ...quirksnaturalfantasy.data.map((item) => item.description),
    ...quirkstechnofantasy.data.map((item) => item.description),
  ],
};
